version: '3'
services:
  # Servicio de base de datos
  db:
    image: mysql:8.0
    container_name: iga_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: iga_db
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Servicio de backend
  backend:
    build: ./backend
    container_name: iga_backend
    volumes:
      - ./backend:/var/www/html
      - ./frontend/public/images:/var/www/html/public/images
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=iga_db
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_DEBUG=true
    depends_on:
      - db

  # Servicio de frontend
  frontend:
    build: ./frontend
    container_name: iga_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: iga_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  dbdata: 